name: TinyStatus Monitor

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 根据项目需求选择版本


      - name: Commit changes
        run: |
          pip install -r requirements.txt
          python -m tinystatus.single

      - name: Archive HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: status-reports
          path: html/  # 输出目录
          retention-days: 7  # 保留7天
